/** Greek translations. Keys are the English UI strings; missing keys fall back to English. */
export const el: Record<string, string> = {
  // Navigation
  Dashboard: 'Πίνακας ελέγχου',
  Products: 'Προϊόντα',
  'Barcode Scanner': 'Barcode Scanner',
  'Stock In': 'Εισαγωγή (Stock In)',
  'Stock Out': 'Εξαγωγή (Stock Out)',
  Inventory: 'Απόθεμα',
  'Low Stock': 'Χαμηλό απόθεμα',
  Transactions: 'Κινήσεις',
  Catalog: 'Κατάλογος',
  Suppliers: 'Προμηθευτές',
  Categories: 'Κατηγορίες',
  'Import / Export': 'Εισαγωγή / Εξαγωγή Excel',
  Reports: 'Αναφορές',
  Administration: 'Διαχείριση',
  'Activity Log': 'Ιστορικό ενεργειών',
  Users: 'Χρήστες',
  Settings: 'Ρυθμίσεις',
  Menu: 'Μενού',
  Scan: 'Σάρωση',
  'Toggle dark mode': 'Σκοτεινό / φωτεινό θέμα',
  'Global search': 'Γενική αναζήτηση',
  'Search barcode, SKU, product, supplier, category…': 'Αναζήτηση barcode, SKU, προϊόντος, προμηθευτή, κατηγορίας…',
  'No results for "{q}"': 'Κανένα αποτέλεσμα για «{q}»',
  'Show all {n} results': 'Όλα τα αποτελέσματα ({n})',
  'Signed in as': 'Συνδεδεμένος ως',
  'Change password': 'Αλλαγή κωδικού',
  'Sign out': 'Αποσύνδεση',
  'Access denied': 'Δεν επιτρέπεται η πρόσβαση',
  'You do not have permission to view this page.': 'Δεν έχετε δικαίωμα πρόσβασης σε αυτή τη σελίδα.',

  // Roles
  Administrator: 'Διαχειριστής',
  Manager: 'Υπεύθυνος',
  'Warehouse user': 'Χρήστης αποθήκης',
  'Full access, including users and settings.': 'Πλήρης πρόσβαση, μαζί με χρήστες και ρυθμίσεις.',
  'Products, inventory, adjustments, import/export and reports.': 'Προϊόντα, απόθεμα, διορθώσεις, εισαγωγή/εξαγωγή Excel και αναφορές.',
  'Barcode scanning, stock in / out and product lookup.': 'Σάρωση barcode, εισαγωγές / εξαγωγές και αναζήτηση προϊόντων.',

  // Login
  'Sign in to continue': 'Συνδεθείτε για να συνεχίσετε',
  Username: 'Όνομα χρήστη',
  Password: 'Κωδικός',
  'Sign in': 'Σύνδεση',

  // Common
  Cancel: 'Ακύρωση',
  Confirm: 'Επιβεβαίωση',
  Close: 'Κλείσιμο',
  Save: 'Αποθήκευση',
  'Save changes': 'Αποθήκευση αλλαγών',
  Create: 'Δημιουργία',
  Edit: 'Επεξεργασία',
  Delete: 'Διαγραφή',
  Clear: 'Καθαρισμός',
  Export: 'Εξαγωγή',
  Import: 'Εισαγωγή',
  Print: 'Εκτύπωση',
  Search: 'Αναζήτηση',
  All: 'Όλα',
  From: 'Από',
  To: 'Έως',
  Today: 'Σήμερα',
  '7 days': '7 ημέρες',
  '30 days': '30 ημέρες',
  '90 days': '90 ημέρες',
  '12 months': '12 μήνες',
  Name: 'Όνομα',
  Description: 'Περιγραφή',
  Notes: 'Σημειώσεις',
  Comments: 'Σχόλια',
  Status: 'Κατάσταση',
  Active: 'Ενεργό',
  Inactive: 'Ανενεργό',
  Disabled: 'Απενεργοποιημένος',
  Date: 'Ημερομηνία',
  Time: 'Ώρα',
  'Date/Time': 'Ημερομηνία/Ώρα',
  User: 'Χρήστης',
  Type: 'Τύπος',
  Reference: 'Αναφορά',
  Reason: 'Αιτιολογία',
  Value: 'Αξία',
  Total: 'Σύνολο',
  Units: 'Τεμάχια',
  Lines: 'Γραμμές',
  Number: 'Αριθμός',
  Details: 'Λεπτομέρειες',
  Code: 'Κωδικός',
  Address: 'Διεύθυνση',
  Phone: 'Τηλέφωνο',
  optional: 'προαιρετικό',
  you: 'εσείς',
  min: 'ελάχ.',
  available: 'διαθέσιμα',
  requested: 'ζητήθηκαν',
  'in stock': 'σε απόθεμα',
  'just now': 'μόλις τώρα',
  '{n} min ago': 'πριν {n} λεπτά',
  '{n} h ago': 'πριν {n} ώρες',
  '{from}–{to} of {total}': '{from}–{to} από {total}',
  'Previous page': 'Προηγούμενη σελίδα',
  'Next page': 'Επόμενη σελίδα',
  'Rows per page': 'Γραμμές ανά σελίδα',
  'View all': 'Όλα',
  'Try changing the search or filters.': 'Δοκιμάστε διαφορετική αναζήτηση ή φίλτρα.',
  Previous: 'Προηγ.',
  New: 'Νέα',
  Change: 'Μεταβολή',
  Difference: 'Διαφορά',
  Min: 'Ελάχ.',
  Price: 'Τιμή',
  Stock: 'Απόθεμα',
  Remaining: 'Υπόλοιπο',
  After: 'Μετά',
  Available: 'Διαθέσιμο',
  Zone: 'Ζώνη',
  Rack: 'Ράφι',
  'Shelf/Bin': 'Θέση/Κελί',
  Confirmed: 'Επιβεβαιωμένο',
  Cancelled: 'Ακυρωμένο',
  Sheet: 'Φύλλο',
  Row: 'Γραμμή',
  Rows: 'Γραμμές',
  Error: 'Σφάλμα',
  Errors: 'Σφάλματα',
  Update: 'Ενημέρωση',
  Skip: 'Παράλειψη',
  Existing: 'Υπάρχοντα',
  Messages: 'Μηνύματα',

  // Stock status & transaction types
  'In stock': 'Σε απόθεμα',
  'Low stock': 'Χαμηλό απόθεμα',
  'Out of stock': 'Εκτός αποθέματος',
  'Stock in': 'Εισαγωγή',
  'Stock out': 'Εξαγωγή',
  'Adjustment +': 'Διόρθωση +',
  'Adjustment −': 'Διόρθωση −',
  'Return in': 'Επιστροφή από πελάτη',
  'Return out': 'Επιστροφή σε προμηθευτή',
  'Initial stock': 'Αρχικό απόθεμα',
  Receipt: 'Παραλαβή',
  Dispatch: 'Αποστολή',
  Adjustment: 'Διόρθωση',
  Product: 'Προϊόν',
  Reversal: 'Αντιλογισμός',
  Manual: 'Χειροκίνητα',
  Reversed: 'Αντιλογίστηκε',
  'Reverse transaction': 'Αντιλογισμός κίνησης',

  // Dashboard
  'Good morning': 'Καλημέρα',
  'Good afternoon': 'Καλό απόγευμα',
  'Good evening': 'Καλησπέρα',
  'Total products': 'Σύνολο προϊόντων',
  '{n} active': '{n} ενεργά',
  'Total stock units': 'Σύνολο τεμαχίων',
  'Total inventory value': 'Αξία αποθέματος',
  'Retail value {v}': 'Αξία λιανικής {v}',
  'Low stock items': 'Χαμηλό απόθεμα',
  'Out of stock items': 'Εκτός αποθέματος',
  'Today stock in': 'Σημερινές εισαγωγές',
  'Today stock out': 'Σημερινές εξαγωγές',
  '{n} movements': '{n} κινήσεις',
  'Transactions today': 'Κινήσεις σήμερα',
  'Stock IN vs Stock OUT': 'Εισαγωγές vs Εξαγωγές',
  'Units per month, last 12 months': 'Τεμάχια ανά μήνα, τελευταίοι 12 μήνες',
  'Movements, last 30 days': 'Κινήσεις, τελευταίες 30 ημέρες',
  'Number of stock transactions per day': 'Αριθμός κινήσεων αποθέματος ανά ημέρα',
  Movements: 'Κινήσεις',
  'Units in': 'Τεμάχια εισόδου',
  'Units out': 'Τεμάχια εξόδου',
  'Inventory value': 'Αξία αποθέματος',
  'End of month, at current purchase prices': 'Στο τέλος κάθε μήνα, σε τρέχουσες τιμές αγοράς',
  'Products by category': 'Προϊόντα ανά κατηγορία',
  'Active products': 'Ενεργά προϊόντα',
  'Recent transactions': 'Πρόσφατες κινήσεις',
  'No transactions yet': 'Δεν υπάρχουν κινήσεις ακόμη',
  'Low stock alerts': 'Ειδοποιήσεις χαμηλού αποθέματος',
  'All products are above minimum stock': 'Όλα τα προϊόντα είναι πάνω από το ελάχιστο απόθεμα',

  // Products
  '{n} products': '{n} προϊόντα',
  'New product': 'Νέο προϊόν',
  'Search barcode, SKU, name…': 'Αναζήτηση barcode, SKU, ονόματος…',
  'All categories': 'Όλες οι κατηγορίες',
  'All suppliers': 'Όλοι οι προμηθευτές',
  'All zones': 'Όλες οι ζώνες',
  'All locations': 'Όλες οι θέσεις',
  'Any stock level': 'Κάθε επίπεδο αποθέματος',
  'Any status': 'Κάθε κατάσταση',
  'No products found': 'Δεν βρέθηκαν προϊόντα',
  'Add your first product or import them from Excel.': 'Προσθέστε το πρώτο σας προϊόν ή εισάγετε προϊόντα από Excel.',
  Barcode: 'Barcode',
  Category: 'Κατηγορία',
  Supplier: 'Προμηθευτής',
  Location: 'Θέση',
  Unit: 'Μονάδα',
  Quantity: 'Ποσότητα',
  'Purchase price': 'Τιμή αγοράς',
  'Selling price': 'Τιμή πώλησης',
  Margin: 'Περιθώριο',
  Created: 'Δημιουργήθηκε',
  'Last updated': 'Τελευταία ενημέρωση',
  'Current stock': 'Τρέχον απόθεμα',
  'Minimum stock': 'Ελάχιστο απόθεμα',
  'Stock value': 'Αξία αποθέματος',
  'Total in': 'Σύνολο εισόδων',
  'Total out': 'Σύνολο εξόδων',
  'Last stock in': 'Τελευταία εισαγωγή',
  'Last stock out': 'Τελευταία εξαγωγή',
  'Adjust stock': 'Διόρθωση αποθέματος',
  'Upload photo': 'Ανέβασμα φωτογραφίας',
  'Photo updated': 'Η φωτογραφία ενημερώθηκε',
  'Product deleted': 'Το προϊόν διαγράφηκε',
  'Product not found': 'Το προϊόν δεν βρέθηκε',
  'Back to products': 'Επιστροφή στα προϊόντα',
  'This barcode is also used by:': 'Το ίδιο barcode χρησιμοποιείται και από:',
  'Stock level over time': 'Εξέλιξη αποθέματος',
  'Quantity after each transaction': 'Ποσότητα μετά από κάθε κίνηση',
  'Stock history': 'Ιστορικό αποθέματος',
  'Full audit trail of every stock movement': 'Πλήρες ιστορικό κάθε κίνησης αποθέματος',
  'No stock movements yet': 'Δεν υπάρχουν κινήσεις ακόμη',
  'Delete product?': 'Διαγραφή προϊόντος;',
  'Products with stock movements cannot be deleted — set them to Inactive instead.':
    'Προϊόντα με κινήσεις αποθέματος δεν διαγράφονται — ορίστε τα ως Ανενεργά.',

  // Product form
  'Edit product': 'Επεξεργασία προϊόντος',
  Identification: 'Στοιχεία αναγνώρισης',
  'Already used by {name}': 'Χρησιμοποιείται ήδη από «{name}»',
  'No spaces allowed': 'Δεν επιτρέπονται κενά',
  'Barcode (EAN / UPC)': 'Barcode (EAN / UPC)',
  'Click the field and scan the product': 'Κάντε κλικ στο πεδίο και σκανάρετε το προϊόν',
  'Also used by {list} — you will be asked to confirm': 'Χρησιμοποιείται και από {list} — θα ζητηθεί επιβεβαίωση',
  'Product name': 'Όνομα προϊόντος',
  Classification: 'Ταξινόμηση',
  'New category': 'Νέα κατηγορία',
  'New supplier': 'Νέος προμηθευτής',
  'Warehouse location': 'Θέση αποθήκης',
  'Zone-Rack-Shelf, e.g. A-01-03': 'Ζώνη-Ράφι-Θέση, π.χ. A-01-03',
  'Stock & prices': 'Απόθεμα & τιμές',
  'Unit of measure': 'Μονάδα μέτρησης',
  'Current quantity': 'Τρέχουσα ποσότητα',
  'Changed only through stock movements or adjustments': 'Αλλάζει μόνο μέσω κινήσεων ή διορθώσεων',
  'Initial quantity': 'Αρχική ποσότητα',
  'Recorded as INITIAL_STOCK': 'Καταγράφεται ως INITIAL_STOCK',
  'Numbers must be zero or positive.': 'Οι αριθμοί πρέπει να είναι μηδέν ή θετικοί.',
  'Create product': 'Δημιουργία προϊόντος',
  'Product saved': 'Το προϊόν αποθηκεύτηκε',
  'Product {sku} created': 'Δημιουργήθηκε το προϊόν {sku}',
  'Duplicate barcode': 'Διπλό barcode',
  'Barcode {code} is already used by: {list}. Save anyway? Scanning this barcode will then ask which product you mean.':
    'Το barcode {code} χρησιμοποιείται ήδη από: {list}. Αποθήκευση παρ’ όλα αυτά; Στη σάρωση θα ερωτάστε ποιο προϊόν εννοείτε.',
  'Save with duplicate barcode': 'Αποθήκευση με διπλό barcode',

  // Adjustments
  'Inventory adjustment': 'Διόρθωση αποθέματος',
  'System quantity': 'Ποσότητα συστήματος',
  'Physical count': 'Φυσική καταμέτρηση',
  Add: 'Προσθήκη',
  Remove: 'Αφαίρεση',
  'Physical quantity (counted)': 'Φυσική ποσότητα (καταμέτρηση)',
  'New quantity': 'Νέα ποσότητα',
  'The quantity would become negative.': 'Η ποσότητα θα γινόταν αρνητική.',
  'Other…': 'Άλλο…',
  'Describe the reason': 'Περιγράψτε την αιτία',
  'Optional, e.g. count sheet or RMA number': 'Προαιρετικό, π.χ. φύλλο απογραφής ή αριθμός RMA',
  'Save adjustment': 'Αποθήκευση διόρθωσης',
  'Counted quantity equals system quantity — no adjustment needed.': 'Η καταμέτρηση συμφωνεί με το σύστημα — δεν χρειάζεται διόρθωση.',
  'Stock of {sku} updated to {qty}': 'Το απόθεμα του {sku} έγινε {qty}',
  'Physical inventory count': 'Φυσική απογραφή',
  'Cycle count correction': 'Διόρθωση κυκλικής καταμέτρησης',
  'Found during count': 'Βρέθηκε στην καταμέτρηση',
  'Correction of wrong entry': 'Διόρθωση λανθασμένης καταχώρησης',
  'Supplier bonus / free goods': 'Δώρο / bonus προμηθευτή',
  'Damaged goods': 'Κατεστραμμένα είδη',
  'Expired goods': 'Ληγμένα είδη',
  'Lost / theft': 'Απώλεια / κλοπή',
  'Internal use / samples': 'Εσωτερική χρήση / δείγματα',
  'Customer return': 'Επιστροφή από πελάτη',
  'Return to supplier': 'Επιστροφή σε προμηθευτή',

  // Scanner
  'Continuous scanning — the field stays ready for the next barcode.': 'Συνεχής σάρωση — το πεδίο μένει έτοιμο για το επόμενο barcode.',
  'Mute sounds': 'Σίγαση ήχων',
  'Enable sounds': 'Ενεργοποίηση ήχων',
  Lookup: 'Αναζήτηση',
  '1 per scan': '1 ανά scan',
  'Fixed qty': 'Σταθερή ποσ.',
  'Ask qty': 'Ερώτηση ποσ.',
  'Quantity per scan': 'Ποσότητα ανά scan',
  'Each scan ADDS {q} to stock.': 'Κάθε scan ΠΡΟΣΘΕΤΕΙ {q} στο απόθεμα.',
  'Each scan REMOVES {q} from stock.': 'Κάθε scan ΑΦΑΙΡΕΙ {q} από το απόθεμα.',
  'the quantity you enter': 'την ποσότητα που θα πληκτρολογήσετε',
  'Scan to view product information without changing stock.': 'Σκανάρετε για προβολή στοιχείων χωρίς αλλαγή αποθέματος.',
  'Scan barcode or type SKU / product name…': 'Σκανάρετε barcode ή γράψτε SKU / όνομα προϊόντος…',
  'Quantity to add': 'Ποσότητα προς προσθήκη',
  'Quantity to remove': 'Ποσότητα προς αφαίρεση',
  'Scan session': 'Τρέχουσα συνεδρία',
  '{n} scans · +{in} in · −{out} out': '{n} σαρώσεις · +{in} είσοδος · −{out} έξοδος',
  'No scans yet': 'Καμία σάρωση ακόμη',
  'Scanned products appear here. You can undo a scan for 30 minutes.': 'Τα σκαναρισμένα προϊόντα εμφανίζονται εδώ. Μπορείτε να αναιρέσετε ένα scan για 30 λεπτά.',
  Undo: 'Αναίρεση',
  'Scan undone': 'Το scan αναιρέθηκε',
  'Not enough stock for {sku}: available {available}, requested {requested}': 'Ανεπαρκές απόθεμα για {sku}: διαθέσιμα {available}, ζητήθηκαν {requested}',
  'No product found for barcode {code}': 'Δεν βρέθηκε προϊόν για το barcode {code}',
  'Several products share barcode {code}': 'Πολλά προϊόντα έχουν το barcode {code}',
  'Choose the product you scanned (or press its number):': 'Επιλέξτε το προϊόν που σκανάρατε (ή πατήστε τον αριθμό του):',
  'Ready to scan': 'Έτοιμο για σάρωση',
  'Use a USB or Bluetooth barcode scanner, or type a barcode / SKU and press Enter.': 'Χρησιμοποιήστε USB ή Bluetooth barcode scanner, ή γράψτε barcode / SKU και πατήστε Enter.',
  'Create product with this barcode': 'Δημιουργία προϊόντος με αυτό το barcode',
  'This scan': 'Αυτό το scan',

  // Stock documents
  'Stock In — Goods receipt': 'Παραλαβή προϊόντων',
  'Stock Out — Dispatch': 'Εξαγωγή προϊόντων',
  'Receive products into the warehouse': 'Καταχώρηση εισερχόμενων προϊόντων στην αποθήκη',
  'Ship products out of the warehouse': 'Καταχώρηση εξερχόμενων προϊόντων από την αποθήκη',
  'New receipt': 'Νέα παραλαβή',
  'New dispatch': 'Νέα εξαγωγή',
  'Receipt history': 'Ιστορικό παραλαβών',
  'Dispatch history': 'Ιστορικό εξαγωγών',
  'Receipt details': 'Στοιχεία παραλαβής',
  'Dispatch details': 'Στοιχεία εξαγωγής',
  'Receipt number': 'Αριθμός παραλαβής',
  'Dispatch number': 'Αριθμός εξαγωγής',
  'Assigned on confirmation': 'Αποδίδεται με την επιβεβαίωση',
  'Invoice / delivery note no.': 'Αρ. τιμολογίου / δελτίου αποστολής',
  'Customer / recipient': 'Πελάτης / παραλήπτης',
  'Order, invoice or delivery note number': 'Αριθμός παραγγελίας, τιμολογίου ή δελτίου',
  'Qty per scan': 'Ποσ. ανά scan',
  'Product {sku} is inactive and cannot be received.': 'Το προϊόν {sku} είναι ανενεργό και δεν μπορεί να παραληφθεί.',
  'No products added': 'Δεν έχουν προστεθεί προϊόντα',
  'Scan barcodes or search products above. Scanning the same product again increases its quantity.':
    'Σκανάρετε barcodes ή αναζητήστε προϊόντα παραπάνω. Νέο scan του ίδιου προϊόντος αυξάνει την ποσότητα.',
  'Unit cost': 'Κόστος μονάδας',
  'Unit price': 'Τιμή μονάδας',
  Decrease: 'Μείωση',
  Increase: 'Αύξηση',
  'Only {n} available': 'Μόνο {n} διαθέσιμα',
  'Remove line': 'Αφαίρεση γραμμής',
  'Warning: {n} line(s) request more than the available stock. Stock cannot become negative.':
    'Προσοχή: {n} γραμμή(ές) ζητούν περισσότερα από το διαθέσιμο απόθεμα. Το απόθεμα δεν μπορεί να γίνει αρνητικό.',
  'Dispatch rejected — insufficient stock': 'Η εξαγωγή απορρίφθηκε — ανεπαρκές απόθεμα',
  'Update purchase prices from this receipt': 'Ενημέρωση τιμών αγοράς από αυτή την παραλαβή',
  'Dispatch anyway': 'Εξαγωγή παρ’ όλα αυτά',
  'Confirm Receipt': 'Επιβεβαίωση παραλαβής',
  'Confirm Dispatch': 'Επιβεβαίωση εξαγωγής',
  'Confirm receipt?': 'Επιβεβαίωση παραλαβής;',
  'Confirm dispatch?': 'Επιβεβαίωση εξαγωγής;',
  '{lines} lines / {qty} units will be ADDED to stock.': '{lines} γραμμές / {qty} τεμάχια θα ΠΡΟΣΤΕΘΟΥΝ στο απόθεμα.',
  '{lines} lines / {qty} units will be REMOVED from stock.': '{lines} γραμμές / {qty} τεμάχια θα ΑΦΑΙΡΕΘΟΥΝ από το απόθεμα.',
  'Receipt confirmed': 'Η παραλαβή επιβεβαιώθηκε',
  'Dispatch confirmed': 'Η εξαγωγή επιβεβαιώθηκε',
  '{lines} lines, {qty} units. Stock has been updated.': '{lines} γραμμές, {qty} τεμάχια. Το απόθεμα ενημερώθηκε.',
  'View / print': 'Προβολή / εκτύπωση',
  'Number, invoice, supplier…': 'Αριθμός, τιμολόγιο, προμηθευτής…',
  'Number, customer, reference…': 'Αριθμός, πελάτης, αναφορά…',
  'Export lines': 'Εξαγωγή γραμμών',
  'No receipts found': 'Δεν βρέθηκαν παραλαβές',
  'No dispatches found': 'Δεν βρέθηκαν εξαγωγές',
  Customer: 'Πελάτης',
  Invoice: 'Τιμολόγιο',
  'Goods receipt': 'Δελτίο παραλαβής',
  'Dispatch note': 'Δελτίο αποστολής',
  'Cancel document': 'Ακύρωση παραστατικού',
  'Cancel {number}?': 'Ακύρωση {number};',
  'All quantities of this receipt will be removed from stock again (reversal transactions).':
    'Όλες οι ποσότητες της παραλαβής θα αφαιρεθούν ξανά από το απόθεμα (κινήσεις αντιλογισμού).',
  'All quantities of this dispatch will be returned to stock (reversal transactions).':
    'Όλες οι ποσότητες της εξαγωγής θα επιστρέψουν στο απόθεμα (κινήσεις αντιλογισμού).',
  'Document cancelled and stock movements reversed': 'Το παραστατικό ακυρώθηκε και οι κινήσεις αντιλογίστηκαν',
  'Document not found': 'Το παραστατικό δεν βρέθηκε',
  'Received by': 'Παρέλαβε',
  'Delivered by': 'Παρέδωσε',
  'Dispatched by': 'Απέστειλε',

  // Inventory
  'Stock per product and warehouse location': 'Απόθεμα ανά προϊόν και θέση αποθήκης',
  'Export inventory': 'Εξαγωγή αποθέματος',
  'Stock count': 'Απογραφή',
  Locations: 'Θέσεις αποθήκης',
  'Scan a product to count it…': 'Σκανάρετε ένα προϊόν για καταμέτρηση…',
  'Count by scanning': 'Καταμέτρηση με scan',
  'Each scan adds 1 to the counted quantity (scan every item).': 'Κάθε scan προσθέτει 1 στην καταμετρημένη ποσότητα (σκανάρετε κάθε τεμάχιο).',
  'Start counting': 'Ξεκινήστε την καταμέτρηση',
  'Scan each product and type the quantity you physically count. Differences are posted as adjustments.':
    'Σκανάρετε κάθε προϊόν και γράψτε την ποσότητα που μετράτε. Οι διαφορές καταχωρούνται ως διορθώσεις.',
  System: 'Σύστημα',
  Counted: 'Καταμετρήθηκαν',
  'Count summary': 'Σύνοψη απογραφής',
  'Products scanned': 'Σκαναρισμένα προϊόντα',
  'With differences': 'Με διαφορές',
  'Post stock count': 'Καταχώρηση απογραφής',
  'Post stock count?': 'Καταχώρηση απογραφής;',
  '{n} products with differences will be adjusted to the counted quantity. Every adjustment is recorded in the transaction history.':
    '{n} προϊόντα με διαφορές θα διορθωθούν στην καταμετρημένη ποσότητα. Κάθε διόρθωση καταγράφεται στο ιστορικό κινήσεων.',
  'Stock count saved: {a} adjusted, {u} unchanged': 'Η απογραφή καταχωρήθηκε: {a} διορθώσεις, {u} χωρίς αλλαγή',
  'Search locations…': 'Αναζήτηση θέσεων…',
  'Format: Zone-Rack-Shelf (e.g. A-01-03)': 'Μορφή: Ζώνη-Ράφι-Θέση (π.χ. A-01-03)',
  'New location': 'Νέα θέση',
  'Edit location': 'Επεξεργασία θέσης',
  'No locations yet': 'Δεν υπάρχουν θέσεις',
  'Locations are also created automatically when you assign one to a product.': 'Οι θέσεις δημιουργούνται και αυτόματα όταν τις ορίζετε σε προϊόν.',
  'Location saved': 'Η θέση αποθηκεύτηκε',
  'Location deleted': 'Η θέση διαγράφηκε',
  'Delete location {code}?': 'Διαγραφή θέσης {code};',

  // Low stock
  'Products at or below their minimum stock level': 'Προϊόντα στο ή κάτω από το ελάχιστο απόθεμα',
  'Receive selected ({n})': 'Παραλαβή επιλεγμένων ({n})',
  'All alerts': 'Όλες οι ειδοποιήσεις',
  'Select all': 'Επιλογή όλων',
  Shortage: 'Έλλειμμα',
  'Suggested order': 'Προτεινόμενη παραγγελία',
  'Nothing to reorder': 'Τίποτα προς παραγγελία',

  // Transactions
  'Complete, immutable history of every stock movement': 'Πλήρες, αμετάβλητο ιστορικό κάθε κίνησης αποθέματος',
  'SKU, product, reference…': 'SKU, προϊόν, αναφορά…',
  'All types': 'Όλοι οι τύποι',
  'All users': 'Όλοι οι χρήστες',
  'No transactions found': 'Δεν βρέθηκαν κινήσεις',
  '{n} transactions': '{n} κινήσεις',
  'Transaction reversed': 'Η κίνηση αντιλογίστηκε',
  'Reverse transaction #{id}?': 'Αντιλογισμός κίνησης #{id};',
  'An opposite adjustment will be posted. The original transaction stays in the history.':
    'Θα καταχωρηθεί αντίθετη διόρθωση. Η αρχική κίνηση παραμένει στο ιστορικό.',
  Reverse: 'Αντιλογισμός',

  // Suppliers & categories
  '{n} suppliers': '{n} προμηθευτές',
  'Products by supplier': 'Προϊόντα ανά προμηθευτή',
  'Search suppliers…': 'Αναζήτηση προμηθευτών…',
  'No suppliers': 'Δεν υπάρχουν προμηθευτές',
  Contact: 'Επικοινωνία',
  'Contact person': 'Υπεύθυνος επικοινωνίας',
  'VAT number': 'ΑΦΜ',
  'Last receipt': 'Τελευταία παραλαβή',
  'Edit supplier': 'Επεξεργασία προμηθευτή',
  'Supplier saved': 'Ο προμηθευτής αποθηκεύτηκε',
  'Supplier deleted': 'Ο προμηθευτής διαγράφηκε',
  'Delete supplier "{name}"?': 'Διαγραφή προμηθευτή «{name}»;',
  'Products of this supplier are kept, without a supplier.': 'Τα προϊόντα του προμηθευτή διατηρούνται, χωρίς προμηθευτή.',
  '{n} categories': '{n} κατηγορίες',
  'No categories': 'Δεν υπάρχουν κατηγορίες',
  'Share of value': 'Ποσοστό αξίας',
  'Edit category': 'Επεξεργασία κατηγορίας',
  'Category saved': 'Η κατηγορία αποθηκεύτηκε',
  'Category deleted': 'Η κατηγορία διαγράφηκε',
  'Delete category "{name}"?': 'Διαγραφή κατηγορίας «{name}»;',
  '{n} products will be left without a category.': '{n} προϊόντα θα μείνουν χωρίς κατηγορία.',

  // Import / export
  'Bulk import products from Excel and export reports': 'Μαζική εισαγωγή προϊόντων από Excel και εξαγωγή αναφορών',
  'Import products': 'Εισαγωγή προϊόντων',
  'Export to Excel': 'Εξαγωγή σε Excel',
  'Upload file': 'Ανέβασμα αρχείου',
  'Map columns': 'Αντιστοίχιση στηλών',
  'Preview & validate': 'Προεπισκόπηση & έλεγχος',
  Result: 'Αποτέλεσμα',
  'Drag & drop an Excel or CSV file here': 'Σύρετε εδώ ένα αρχείο Excel ή CSV',
  'Choose file': 'Επιλογή αρχείου',
  'Excel template': 'Πρότυπο Excel',
  'Download a ready-made template with the correct columns and instructions.': 'Κατεβάστε έτοιμο πρότυπο με τις σωστές στήλες και οδηγίες.',
  'Download Excel Template': 'Λήψη προτύπου Excel',
  'Supported columns': 'Υποστηριζόμενες στήλες',
  'Columns are detected automatically (English or Greek headers); you can adjust the mapping in the next step.':
    'Οι στήλες αναγνωρίζονται αυτόματα (ελληνικές ή αγγλικές επικεφαλίδες)· μπορείτε να αλλάξετε την αντιστοίχιση στο επόμενο βήμα.',
  'Unsupported file type. Please upload .xlsx, .xls or .csv': 'Μη υποστηριζόμενος τύπος αρχείου. Ανεβάστε .xlsx, .xls ή .csv',
  'The file has no data rows': 'Το αρχείο δεν έχει γραμμές δεδομένων',
  '{file} — {n} data rows': '{file} — {n} γραμμές δεδομένων',
  'Column in file': 'Στήλη αρχείου',
  'Import as': 'Εισαγωγή ως',
  'Sample values': 'Ενδεικτικές τιμές',
  '— Ignore —': '— Αγνόηση —',
  SKU: 'SKU',
  'Product Name': 'Όνομα προϊόντος',
  'Minimum Stock': 'Ελάχιστο απόθεμα',
  'Purchase Price': 'Τιμή αγοράς',
  'Selling Price': 'Τιμή πώλησης',
  'If the SKU or barcode already exists': 'Αν το SKU ή το barcode υπάρχει ήδη',
  'Update existing': 'Ενημέρωση υπάρχοντος',
  'Ask me': 'Να ερωτηθώ',
  'Quantity column for existing products': 'Στήλη ποσότητας για υπάρχοντα προϊόντα',
  'Every stock change is recorded as a transaction': 'Κάθε αλλαγή αποθέματος καταγράφεται ως κίνηση',
  "Don't change stock": 'Χωρίς αλλαγή αποθέματος',
  'Set as current stock (adjustment)': 'Ορισμός ως τρέχον απόθεμα (διόρθωση)',
  'Add to stock (Stock IN)': 'Προσθήκη στο απόθεμα (Stock IN)',
  'Create missing categories and suppliers': 'Δημιουργία κατηγοριών και προμηθευτών που λείπουν',
  'Choose another file': 'Άλλο αρχείο',
  'Map the SKU column to continue': 'Αντιστοιχίστε τη στήλη SKU για να συνεχίσετε',
  'Validate {n} rows': 'Έλεγχος {n} γραμμών',
  'New products': 'Νέα προϊόντα',
  'Already exist': 'Υπάρχουν ήδη',
  'With errors': 'Με σφάλματα',
  'Update all existing': 'Ενημέρωση όλων των υπαρχόντων',
  'Skip all existing': 'Παράλειψη όλων των υπαρχόντων',
  'Back to mapping': 'Πίσω στην αντιστοίχιση',
  '{n} rows with errors will be skipped': '{n} γραμμές με σφάλματα θα παραλειφθούν',
  'Import {n} valid rows': 'Εισαγωγή {n} έγκυρων γραμμών',
  'No rows in this view': 'Δεν υπάρχουν γραμμές σε αυτή την προβολή',
  'Showing first {n} rows': 'Εμφανίζονται οι πρώτες {n} γραμμές',
  'Import completed': 'Η εισαγωγή ολοκληρώθηκε',
  Imported: 'Εισήχθησαν',
  Updated: 'Ενημερώθηκαν',
  Skipped: 'Παραλείφθηκαν',
  'New categories': 'Νέες κατηγορίες',
  'New suppliers': 'Νέοι προμηθευτές',
  'Import another file': 'Εισαγωγή άλλου αρχείου',
  'View products': 'Προβολή προϊόντων',
  'All products': 'Όλα τα προϊόντα',
  'Every product, in the import template layout (edit and re-import).': 'Όλα τα προϊόντα, στη μορφή του προτύπου (επεξεργασία και επανεισαγωγή).',
  'Current inventory': 'Τρέχον απόθεμα',
  'Stock per product with location and value, sorted by location.': 'Απόθεμα ανά προϊόν με θέση και αξία, ταξινομημένο ανά θέση.',
  'Low stock products': 'Προϊόντα με χαμηλό απόθεμα',
  'Products at or below minimum stock, with suggested order quantity.': 'Προϊόντα στο ή κάτω από το ελάχιστο, με προτεινόμενη ποσότητα παραγγελίας.',
  'Summary sheet plus one sheet per category.': 'Φύλλο σύνοψης και ένα φύλλο ανά κατηγορία.',
  'Summary sheet plus one sheet per supplier.': 'Φύλλο σύνοψης και ένα φύλλο ανά προμηθευτή.',
  'Stock movement history': 'Ιστορικό κινήσεων αποθέματος',
  'All inventory transactions in the period.': 'Όλες οι κινήσεις αποθέματος της περιόδου.',
  'Stock IN': 'Εισαγωγές (Stock IN)',
  'Stock-in transactions in the period.': 'Κινήσεις εισαγωγής της περιόδου.',
  'Stock OUT': 'Εξαγωγές (Stock OUT)',
  'Stock-out transactions in the period.': 'Κινήσεις εξαγωγής της περιόδου.',
  'Goods receipts (lines)': 'Παραλαβές (γραμμές)',
  'Receipt documents with supplier and invoice.': 'Παραστατικά παραλαβής με προμηθευτή και τιμολόγιο.',
  'Dispatches (lines)': 'Εξαγωγές (γραμμές)',
  'Dispatch documents with customer and reference.': 'Παραστατικά εξαγωγής με πελάτη και αναφορά.',
  'Catalog & stock': 'Κατάλογος & απόθεμα',
  'Current state': 'Τρέχουσα κατάσταση',
  'For a date range': 'Για χρονικό διάστημα',

  // Reports
  'Warehouse movements and stock valuation': 'Κινήσεις αποθήκης και αποτίμηση αποθέματος',
  'Export movements': 'Εξαγωγή κινήσεων',
  'Units received': 'Τεμάχια που παραλήφθηκαν',
  'Units dispatched': 'Τεμάχια που εξήχθησαν',
  'Returns (in / out)': 'Επιστροφές (είσοδος / έξοδος)',
  'Adjustments (+ / −)': 'Διορθώσεις (+ / −)',
  'Stock IN vs Stock OUT per day': 'Εισαγωγές vs Εξαγωγές ανά ημέρα',
  Adjustments: 'Διορθώσεις',
  'Top dispatched products': 'Προϊόντα με τις περισσότερες εξαγωγές',
  'Top received products': 'Προϊόντα με τις περισσότερες παραλαβές',
  'By units in the period': 'Σε τεμάχια για την περίοδο',
  'Sales value': 'Αξία πωλήσεων',
  'Cost value': 'Αξία κόστους',
  'Retail value': 'Αξία λιανικής',
  'Movements by type': 'Κινήσεις ανά τύπο',
  'Activity by user': 'Δραστηριότητα ανά χρήστη',
  'Inventory adjustments': 'Διορθώσεις αποθέματος',
  'Differences found and corrected in the period': 'Διαφορές που εντοπίστηκαν και διορθώθηκαν',
  'No adjustments in this period': 'Δεν υπάρχουν διορθώσεις στην περίοδο',
  'Stock without sales': 'Απόθεμα χωρίς κίνηση',
  'No stock out in the period, highest value first': 'Χωρίς εξαγωγή στην περίοδο, με σειρά αξίας',
  'Every product with stock moved in this period': 'Όλα τα προϊόντα με απόθεμα κινήθηκαν στην περίοδο',
  'No data for this period': 'Δεν υπάρχουν δεδομένα για την περίοδο',
  'Stock valuation': 'Αποτίμηση αποθέματος',
  'Current stock of active products': 'Τρέχον απόθεμα ενεργών προϊόντων',
  'Stock alerts': 'Ειδοποιήσεις',

  // Activity log
  'Who did what, when and from where': 'Ποιος έκανε τι, πότε και από πού',
  'Description, user…': 'Περιγραφή, χρήστης…',
  Action: 'Ενέργεια',
  'All actions': 'Όλες οι ενέργειες',
  'No activity found': 'Δεν βρέθηκαν ενέργειες',
  '{n} entries': '{n} εγγραφές',
  'Previous value': 'Προηγούμενη τιμή',
  'New value': 'Νέα τιμή',

  // Users
  'Accounts and access roles': 'Λογαριασμοί και ρόλοι πρόσβασης',
  'New user': 'Νέος χρήστης',
  'Edit user': 'Επεξεργασία χρήστη',
  Role: 'Ρόλος',
  'Last login': 'Τελευταία σύνδεση',
  'Full name': 'Ονοματεπώνυμο',
  'Letters, digits, . - _': 'Γράμματα, ψηφία, . - _',
  'New password': 'Νέος κωδικός',
  'Leave empty to keep the current password': 'Αφήστε κενό για να διατηρηθεί ο τρέχων κωδικός',
  'At least 8 characters': 'Τουλάχιστον 8 χαρακτήρες',
  'Account active': 'Ενεργός λογαριασμός',
  'Disabled users cannot sign in; their history is kept.': 'Οι απενεργοποιημένοι χρήστες δεν συνδέονται· το ιστορικό τους διατηρείται.',
  'User saved': 'Ο χρήστης αποθηκεύτηκε',

  // Settings & profile
  Appearance: 'Εμφάνιση',
  'Saved on this device': 'Αποθηκεύεται σε αυτή τη συσκευή',
  Theme: 'Θέμα',
  Light: 'Φωτεινό',
  Dark: 'Σκοτεινό',
  Language: 'Γλώσσα',
  'Barcode scanner': 'Barcode scanner',
  'Sound feedback on scan': 'Ηχητική ένδειξη στη σάρωση',
  'Short beep on success, low double tone on errors.': 'Σύντομο μπιπ σε επιτυχία, διπλός χαμηλός τόνος σε σφάλμα.',
  'Test success': 'Δοκιμή επιτυχίας',
  'Test error': 'Δοκιμή σφάλματος',
  'USB and Bluetooth scanners in keyboard (HID) mode work without drivers. Configure the scanner to send Enter after each code. Scans are also caught when no field has focus.':
    'Οι USB και Bluetooth scanners σε λειτουργία πληκτρολογίου (HID) δουλεύουν χωρίς drivers. Ρυθμίστε τον scanner να στέλνει Enter μετά από κάθε κωδικό. Οι σαρώσεις αναγνωρίζονται και όταν δεν είναι επιλεγμένο κάποιο πεδίο.',
  General: 'Γενικά',
  'Company name': 'Επωνυμία εταιρείας',
  Currency: 'Νόμισμα',
  'Default unit': 'Προεπιλεγμένη μονάδα',
  'Allow negative stock (not recommended)': 'Να επιτρέπεται αρνητικό απόθεμα (δεν συνιστάται)',
  'When enabled, dispatches exceeding available stock can be forced after a warning.':
    'Όταν είναι ενεργό, εξαγωγές πάνω από το διαθέσιμο απόθεμα μπορούν να γίνουν μετά από προειδοποίηση.',
  'Settings saved': 'Οι ρυθμίσεις αποθηκεύτηκαν',
  Warehouse: 'Αποθήκη',
  'The database supports multiple warehouses; this installation uses the default one.':
    'Η βάση δεδομένων υποστηρίζει πολλές αποθήκες· η εγκατάσταση χρησιμοποιεί την προεπιλεγμένη.',
  'Warehouse saved': 'Η αποθήκη αποθηκεύτηκε',
  'My account': 'Ο λογαριασμός μου',
  'Current password': 'Τρέχων κωδικός',
  'Confirm new password': 'Επιβεβαίωση νέου κωδικού',
  'Passwords do not match': 'Οι κωδικοί δεν ταιριάζουν',
  'Password changed. Other sessions have been signed out.': 'Ο κωδικός άλλαξε. Οι άλλες συνεδρίες αποσυνδέθηκαν.',

  // Server messages
  'Invalid username or password': 'Λάθος όνομα χρήστη ή κωδικός',
  'This account is disabled': 'Ο λογαριασμός είναι απενεργοποιημένος',
  'Authentication required': 'Απαιτείται σύνδεση',
  'Session expired, please sign in again': 'Η συνεδρία έληξε, συνδεθείτε ξανά',
  'Session is no longer valid': 'Η συνεδρία δεν είναι πλέον έγκυρη',
  'Too many login attempts. Try again in a few minutes.': 'Πάρα πολλές προσπάθειες σύνδεσης. Δοκιμάστε ξανά σε λίγα λεπτά.',
  'You do not have permission to perform this action': 'Δεν έχετε δικαίωμα για αυτή την ενέργεια',
  'Current password is incorrect': 'Ο τρέχων κωδικός είναι λάθος',
  'Username already exists': 'Το όνομα χρήστη υπάρχει ήδη',
  'Category already exists': 'Η κατηγορία υπάρχει ήδη',
  'Supplier already exists': 'Ο προμηθευτής υπάρχει ήδη',
  'At least one active administrator is required': 'Απαιτείται τουλάχιστον ένας ενεργός διαχειριστής',
  'You cannot remove your own admin role or deactivate yourself': 'Δεν μπορείτε να αφαιρέσετε τον δικό σας ρόλο διαχειριστή ή να απενεργοποιήσετε τον εαυτό σας',
  'This product has stock movements and cannot be deleted without losing history. Set it to Inactive instead.':
    'Το προϊόν έχει κινήσεις αποθέματος και δεν μπορεί να διαγραφεί χωρίς απώλεια ιστορικού. Ορίστε το ως Ανενεργό.',
  'You can only undo your own scans from the last 30 minutes': 'Μπορείτε να αναιρέσετε μόνο δικά σας scans των τελευταίων 30 λεπτών',
  'This transaction has already been reversed': 'Η κίνηση έχει ήδη αντιλογιστεί',
  'This transaction belongs to a document. Cancel the whole document instead.': 'Η κίνηση ανήκει σε παραστατικό. Ακυρώστε ολόκληρο το παραστατικό.',
  'Only JPG, PNG, WEBP or GIF images are allowed': 'Επιτρέπονται μόνο εικόνες JPG, PNG, WEBP ή GIF',
  'File is too large': 'Το αρχείο είναι πολύ μεγάλο',

  // First run, backups & desktop
  'Welcome to Warehouse IMS': 'Καλώς ήρθατε στο Warehouse IMS',
  'Hello {name}. The warehouse is empty — choose how to start.': 'Γεια σας {name}. Η αποθήκη είναι άδεια — επιλέξτε πώς θα ξεκινήσετε.',
  'Try it with demo data': 'Δοκιμή με demo δεδομένα',
  '78 sample products, suppliers and 12 months of stock movements, to learn the app before entering real data.':
    '78 δοκιμαστικά προϊόντα, προμηθευτές και 12 μήνες κινήσεων, για να μάθετε την εφαρμογή πριν περάσετε πραγματικά δεδομένα.',
  'Load demo data': 'Φόρτωση demo δεδομένων',
  'Demo data loaded: {n} products': 'Φορτώθηκαν demo δεδομένα: {n} προϊόντα',
  'Import your products from Excel': 'Εισαγωγή των προϊόντων σας από Excel',
  'Download the template, fill in SKU, barcode, name, quantity and the other columns, then upload it.':
    'Κατεβάστε το πρότυπο, συμπληρώστε SKU, barcode, όνομα, ποσότητα και τις υπόλοιπες στήλες και ανεβάστε το.',
  'Open Excel import': 'Άνοιγμα Excel import',
  'Add products one by one': 'Προσθήκη προϊόντων ένα-ένα',
  'Scan the barcode into the form and enter the opening quantity.': 'Σκανάρετε το barcode στη φόρμα και γράψτε την αρχική ποσότητα.',
  'No products yet': 'Δεν υπάρχουν προϊόντα ακόμη',
  'Ask a manager to add products or import them from Excel.': 'Ζητήστε από έναν υπεύθυνο να προσθέσει προϊόντα ή να τα εισάγει από Excel.',
  'You are using a temporary or default password. Change it now so nobody else can sign in as you.':
    'Χρησιμοποιείτε προσωρινό ή προεπιλεγμένο κωδικό. Αλλάξτε τον τώρα, ώστε να μην μπορεί κανείς άλλος να συνδεθεί ως εσείς.',
  Backups: 'Αντίγραφα ασφαλείας (backup)',
  'A copy of the whole database is saved automatically once a day.': 'Αντίγραφο ολόκληρης της βάσης αποθηκεύεται αυτόματα μία φορά την ημέρα.',
  'Back up now': 'Backup τώρα',
  'Backup saved: {name}': 'Το backup αποθηκεύτηκε: {name}',
  'Backup settings saved': 'Οι ρυθμίσεις backup αποθηκεύτηκαν',
  'Last backup': 'Τελευταίο backup',
  never: 'ποτέ',
  'Backup folder': 'Φάκελος backup',
  'Empty = default folder: {dir}. Choose a USB stick, second disk or OneDrive folder for extra safety.':
    'Κενό = προεπιλεγμένος φάκελος: {dir}. Για μεγαλύτερη ασφάλεια επιλέξτε USB stick, δεύτερο δίσκο ή φάκελο OneDrive.',
  'Choose folder': 'Επιλογή φακέλου',
  'Keep last': 'Διατήρηση τελευταίων',
  backups: 'αντιγράφων',
  'Automatic daily backup': 'Αυτόματο ημερήσιο backup',
  'Recommended. Old backups beyond the number above are deleted automatically.': 'Συνιστάται. Τα παλαιότερα backup πέρα από τον παραπάνω αριθμό διαγράφονται αυτόματα.',
  'Open backup folder': 'Άνοιγμα φακέλου backup',
  'Restore from file…': 'Επαναφορά από αρχείο…',
  Size: 'Μέγεθος',
  Automatic: 'Αυτόματο',
  'Before restore': 'Πριν την επαναφορά',
  Download: 'Λήψη',
  'Restore this backup': 'Επαναφορά αυτού του backup',
  'Restore backup?': 'Επαναφορά backup;',
  'All current data will be replaced by "{name}". A backup of the current data is taken first, so you can undo this. Everyone will be signed out.':
    'Όλα τα τρέχοντα δεδομένα θα αντικατασταθούν από το «{name}». Πρώτα κρατείται backup των τρεχόντων δεδομένων, ώστε να μπορείτε να το αναιρέσετε. Όλοι οι χρήστες θα αποσυνδεθούν.',
  Restore: 'Επαναφορά',
  'Backup restored. Sign in again to continue.': 'Η επαναφορά ολοκληρώθηκε. Συνδεθείτε ξανά για να συνεχίσετε.',
  'This file is not a valid Warehouse IMS backup': 'Το αρχείο δεν είναι έγκυρο backup του Warehouse IMS',
  'Demo data can only be loaded into an empty database': 'Τα demo δεδομένα φορτώνονται μόνο σε άδεια βάση',
  'The new password must be different from the current one': 'Ο νέος κωδικός πρέπει να διαφέρει από τον τρέχοντα',
  'Before demo data (empty)': 'Πριν τα demo δεδομένα (άδεια βάση)',
  // Live updates & reliability
  Live: 'Ζωντανά',
  Offline: 'Εκτός σύνδεσης',
  'Reconnecting…': 'Επανασύνδεση…',
  'Connecting…': 'Σύνδεση…',
  'Changes from other PCs appear automatically': 'Οι αλλαγές από άλλους υπολογιστές εμφανίζονται αυτόματα',
  'Connection lost. Check the network and try again.': 'Η σύνδεση χάθηκε. Ελέγξτε το δίκτυο και δοκιμάστε ξανά.',
  'This request key was already used for another action': 'Το ίδιο αίτημα έχει ήδη χρησιμοποιηθεί για άλλη ενέργεια',
};
